export enum MembershipTier {
  BASIC = 'BASIC',
  ESSENTIAL = 'ESSENTIAL',
  PREMIUM = 'PREMIUM'
}

export enum MembershipStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED'
}

export enum AccountRequestType {
  UPGRADE_MEMBERSHIP = 'UPGRADE_MEMBERSHIP',
  DOWNGRADE_MEMBERSHIP = 'DOWNGRADE_MEMBERSHIP',
  CANCEL_MEMBERSHIP = 'CANCEL_MEMBERSHIP',
  ROLE_CHANGE = 'ROLE_CHANGE',
  OTHER = 'OTHER'
}

export enum AccountRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}