export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  DISCONTINUED = 'DISCONTINUED'
}

export enum ProductCategory {
  SUPPLEMENTS = 'SUPPLEMENTS',
  VITAMINS = 'VITAMINS',
  MINERALS = 'MINERALS',
  HERBS = 'HERBS',
  PROTEIN = 'PROTEIN',
  WELLNESS = 'WELLNESS',
  FITNESS = 'FITNESS',
  OTHER = 'OTHER'
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT'
}